name: build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
          
      - name: Clean public
        run: rm -rf public/*      

      - name: Build
        run: hugo --minify

      - name: Copy algolia_uploader to public
        run: |
          mkdir -p public/.github/workflows
          cp .github/workflows/algolia_uploader.yml public/.github/workflows/algolia_uploader.yml

      - name: Pushes to public repository
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: public
          destination-github-username: 'anntsai2356'
          destination-repository-name: 'anntsai2356.github.io'
          user-email: hikarunost@gmail.com
          commit-message: pushed from blog_base
          target-branch: main
